var jsdcontenturl = "https://makale.ahmetozer.org/"
var jsdauthor = "Ahmet OZER";
var jsdwriteurl = jsdcontenturl + "writes";
var jsdthemeurl = jsdcontenturl + "theme/";
var jsdheadertext = ".post-title";
var jsdtextareaid = '#jstextengine';
var jsdheaderimage = "jstextenginebgimg";
var jsdremoveurl = 4;
var jsdauthorid = ".jsdwriter";
var jsdhome = "https://ahmetozer.org/yazi";
var jsdhomeid ="#jsdhome";
var jsdprofileimg = "#jsdprofileimg";
var jsdfacebookurl = "https://www.facebook.com/ahmetozerorg";
var jsdtwitterurl = "https://twitter.com/ahmetozer_org";
var jsdyoutubeurl = "https://www.youtube.com/channel/UCdcAyH3NAd4NbceqsJ4Rnpw";
var jsdflickrurl = "https://www.flickr.com/people/140865607@N08/";
var jsdinstagramurl = "https://www.instagram.com/ahmetozer_org/";
var jsdlinkedinurl = "https://tr.linkedin.com/in/ahmet-ozer";
var jsdyazilar = ["/2017/merhaba", "/network/nat4464", "/project-view/ntp-havuzuna-destek", "/project-view/home-router"];